In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Data for sql and python.csv")

In [4]:
df

,Customer ID,Customer Name,Age,Gender,City,Product ID,Product Name,Brand,Shopping App,Quantity,Unit Selling Price,Total Amount Paid,Purchase Date,Payment Method,Order Status,Customer Rating
0,CUST00001,Rohan Patel,43.0,Other,Mumbai,64,H&M Women Solid Kurta,H&M,Ajio,1,486.1150,486.12,07-04-2025,Debit Card,Returned,1.0
1,CUST00002,Simran Reddy,20.0,Male,Kolkata,1031,Nike Unisex Ripped Jacket,Nike,Flipkart,1,198.2280,198.23,03-04-2025,Cash on Delivery,Delivered,1.0
2,CUST00003,Ayaan Iyer,55.0,Male,Lucknow,939,Allen Solly Kids Ripped Hoodie,Allen Solly,Nykaa Fashion,1,398.4960,398.50,15-08-2025,UPI,Returned,3.0
3,CUST00004,Anika Chopra,27.0,Other,Delhi,365,Biba Kids Solid Track Pants,Biba,Snapdeal,1,466.9020,466.90,05-07-2025,UPI,Returned,4.0
4,CUST00005,Pooja Singh,53.0,Other,Delhi,613,Levi's Kids Cotton Kurta,Levi's,Meesho,1,374.6480,374.65,30-07-2025,Net Banking,Cancelled,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,CUST01196,Krishna Sharma,53.0,Other,Bengaluru,140,Gap Unisex Formal Skirt,Gap,Myntra,3,1895.8740,5687.62,09-05-2026,Credit Card,Delivered,4.0
1196,CUST01197,Amit Singh,53.0,Other,Surat,1019,Under Armour Men Classic Shorts,Under Armour,Flipkart,2,432.7535,865.51,27-11-2025,Net Banking,Delivered,4.0
1197,CUST01198,Yash Joshi,49.0,Male,Jaipur,638,Roadster Men Formal Blazer,Roadster,Nykaa Fashion,1,285.4550,285.45,29-03-2026,Credit Card,Delivered,4.0
1198,CUST01199,Vivaan Sharma,45.0,Other,Pune,141,Van Heusen Women Cotton Jeans,Van Heusen,Myntra,1,473.7450,473.75,18-02-2026,Debit Card,Delivered,5.0
1199,CUST01200,Meera Reddy,27.0,Male,Delhi,654,Forever 21 Men Solid Kurta,Forever 21,Meesho,1,1314.2250,1314.22,30-10-2025,Net Banking,Delivered,5.0

In [5]:
df.head()

,Customer ID,Customer Name,Age,Gender,City,Product ID,Product Name,Brand,Shopping App,Quantity,Unit Selling Price,Total Amount Paid,Purchase Date,Payment Method,Order Status,Customer Rating
0,CUST00001,Rohan Patel,43.0,Other,Mumbai,64,H&M Women Solid Kurta,H&M,Ajio,1,486.115,486.12,07-04-2025,Debit Card,Returned,1.0
1,CUST00002,Simran Reddy,20.0,Male,Kolkata,1031,Nike Unisex Ripped Jacket,Nike,Flipkart,1,198.228,198.23,03-04-2025,Cash on Delivery,Delivered,1.0
2,CUST00003,Ayaan Iyer,55.0,Male,Lucknow,939,Allen Solly Kids Ripped Hoodie,Allen Solly,Nykaa Fashion,1,398.496,398.50,15-08-2025,UPI,Returned,3.0
3,CUST00004,Anika Chopra,27.0,Other,Delhi,365,Biba Kids Solid Track Pants,Biba,Snapdeal,1,466.902,466.90,05-07-2025,UPI,Returned,4.0
4,CUST00005,Pooja Singh,53.0,Other,Delhi,613,Levi's Kids Cotton Kurta,Levi's,Meesho,1,374.648,374.65,30-07-2025,Net Banking,Cancelled,NaN

In [6]:
df.tail()

,Customer ID,Customer Name,Age,Gender,City,Product ID,Product Name,Brand,Shopping App,Quantity,Unit Selling Price,Total Amount Paid,Purchase Date,Payment Method,Order Status,Customer Rating
1195,CUST01196,Krishna Sharma,53.0,Other,Bengaluru,140,Gap Unisex Formal Skirt,Gap,Myntra,3,1895.8740,5687.62,09-05-2026,Credit Card,Delivered,4.0
1196,CUST01197,Amit Singh,53.0,Other,Surat,1019,Under Armour Men Classic Shorts,Under Armour,Flipkart,2,432.7535,865.51,27-11-2025,Net Banking,Delivered,4.0
1197,CUST01198,Yash Joshi,49.0,Male,Jaipur,638,Roadster Men Formal Blazer,Roadster,Nykaa Fashion,1,285.4550,285.45,29-03-2026,Credit Card,Delivered,4.0
1198,CUST01199,Vivaan Sharma,45.0,Other,Pune,141,Van Heusen Women Cotton Jeans,Van Heusen,Myntra,1,473.7450,473.75,18-02-2026,Debit Card,Delivered,5.0
1199,CUST01200,Meera Reddy,27.0,Male,Delhi,654,Forever 21 Men Solid Kurta,Forever 21,Meesho,1,1314.2250,1314.22,30-10-2025,Net Banking,Delivered,5.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         1200 non-null   object
 1   Customer Name       1200 non-null   object
 2   Age                 1200 non-null   float64
 3   Gender              1200 non-null   object
 4   City                1200 non-null   object
 5   Product ID          1200 non-null   int64
 6   Product Name        1200 non-null   object
 7   Brand               1200 non-null   object
 8   Shopping App        1200 non-null   object
 9   Quantity            1200 non-null   int64
 10  Unit Selling Price  1200 non-null   float64
 11  Total Amount Paid   1200 non-null   float64
 12  Purchase Date       1200 non-null   object
 13  Payment Method      1200 non-null   object
 14  Order Status        1200 non-null   object
 15  Customer Rating     1082 non-null   float64
dtypes: float64(4), int64(2), object(10)
memory usage: 150.1+ KB

In [8]:
df.describe()

,Age,Product ID,Quantity,Unit Selling Price,Total Amount Paid,Customer Rating
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1082.000000
mean,36.941667,532.383333,1.239167,696.598893,968.854200,3.575786
std,10.891148,324.361344,0.490408,819.282316,1472.092571,1.431858
min,18.000000,2.000000,1.000000,160.588000,160.590000,1.000000
25%,28.000000,259.000000,1.000000,320.040000,345.150000,2.000000
50%,37.000000,492.500000,1.000000,397.968000,411.650000,4.000000
75%,47.000000,790.000000,1.000000,473.444250,760.822500,5.000000
max,55.000000,1194.000000,3.000000,4653.150000,10745.920000,5.000000

In [9]:
df['City']

0          Mumbai
1         Kolkata
2         Lucknow
3           Delhi
4           Delhi
          ...
1195    Bengaluru
1196        Surat
1197       Jaipur
1198         Pune
1199        Delhi
Name: City, Length: 1200, dtype: object

In [13]:
df[df["City"]=="Pune"].count()

Customer ID           73
Customer Name         73
Age                   73
Gender                73
City                  73
Product ID            73
Product Name          73
Brand                 73
Shopping App          73
Quantity              73
Unit Selling Price    73
Total Amount Paid     73
Purchase Date         73
Payment Method        73
Order Status          73
Customer Rating       67
dtype: int64

In [22]:
df[(df["City"]=="Pune") & (df["Total Amount Paid"]>760)]

,Customer ID,Customer Name,Age,Gender,City,Product ID,Product Name,Brand,Shopping App,Quantity,Unit Selling Price,Total Amount Paid,Purchase Date,Payment Method,Order Status,Customer Rating
176,CUST00177,Diya Malhotra,40.0,Male,Pune,1084,Allen Solly Unisex Ripped Sweater,Allen Solly,Myntra,2,1089.3375,2178.68,21-06-2025,Cash on Delivery,Cancelled,2.0
193,CUST00194,Aarav Sharma,25.0,Male,Pune,410,Under Armour Women Graphic Co-ord Set,Under Armour,Flipkart,1,4236.9840,4236.98,29-04-2026,UPI,Delivered,4.0
327,CUST00328,Myra Joshi,27.0,Male,Pune,306,W Women Solid Hoodie,W,Snapdeal,2,396.5950,793.19,10-04-2026,Net Banking,Delivered,5.0
402,CUST00403,Priya Das,43.0,Other,Pune,495,HRX Unisex Formal Shorts,HRX,Snapdeal,1,1162.4300,1162.43,29-05-2026,Credit Card,Delivered,1.0
514,CUST00515,Anika Agarwal,31.0,Other,Pune,1021,Zara Men Oversized Kurta,Zara,Myntra,2,493.1650,986.33,21-07-2025,Debit Card,Shipped,4.0
525,CUST00526,Isha Malhotra,30.0,Male,Pune,276,Uniqlo Men Ripped Track Pants,Uniqlo,Amazon,3,2173.5360,6520.61,25-09-2025,Credit Card,Delivered,1.0
593,CUST00594,Aadhya Malhotra,48.0,Other,Pune,474,Levi's Men Oversized Blazer,Levi's,Nykaa Fashion,1,822.3960,822.40,18-06-2026,Wallet,Delivered,NaN
654,CUST00655,Sneha Gupta,47.0,Other,Pune,867,Allen Solly Kids Slim Fit Dress,Allen Solly,Myntra,1,3453.4640,3453.46,18-11-2025,Wallet,Delivered,1.0
711,CUST00712,Tanvi Bansal,23.0,Female,Pune,736,Peter England Men Relaxed Fit Sweater,Peter England,Nykaa Fashion,1,2414.2350,2414.24,25-02-2026,Credit Card,Delivered,4.0
787,CUST00788,Ishaan Verma,45.0,Other,Pune,31,W Unisex Relaxed Fit T-Shirt,W,Myntra,2,409.2725,818.54,01-04-2026,Wallet,Returned,5.0
867,CUST00868,Ananya Malhotra,40.0,Male,Pune,196,Allen Solly Men Cotton Jacket,Allen Solly,Meesho,2,426.1920,852.38,26-01-2026,Debit Card,Delivered,4.0
1017,CUST01018,Vivaan Iyer,37.0,Other,Pune,95,Puma Women Classic Jacket,Puma,Flipkart,2,783.3350,1566.67,18-08-2025,Cash on Delivery,Delivered,2.0
1143,CUST01144,Ishaan Sharma,54.0,Female,Pune,689,Peter England Unisex Relaxed Fit Saree,Peter England,Snapdeal,1,2399.7675,2399.77,24-04-2026,Net Banking,Delivered,5.0
1147,CUST01148,Divya Reddy,44.0,Other,Pune,50,Under Armour Men Denim Hoodie,Under Armour,Snapdeal,1,3856.2120,3856.21,03-03-2025,Debit Card,Delivered,2.0
1159,CUST01160,Tanvi Rao,41.0,Female,Pune,1194,Allen Solly Men Formal Skirt,Allen Solly,Amazon,3,2839.5990,8518.80,30-03-2026,Debit Card,Delivered,5.0
1168,CUST01169,Yash Iyer,37.0,Other,Pune,819,Peter England Men Denim Shirt,Peter England,Meesho,1,1559.4390,1559.44,30-10-2025,Wallet,Delivered,5.0